# Generated by Django 3.2.12 on 2024-05-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id_ramo', models.AutoField(db_column='idRamo', primary_key=True, serialize=False)),
                ('ramo', models.CharField(max_length=20)),
                ('creditos', models.IntegerField()),
                ('escuela', models.CharField(max_length=45)),
            ],
        ),
    ]
