# Generated by Django 3.2.12 on 2024-05-31 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_ramo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.AutoField(db_column='idSeccion', primary_key=True, serialize=False)),
                ('codigo_seccion', models.CharField(max_length=20)),
                ('id_ramo', models.ForeignKey(db_column='idRamo', on_delete=django.db.models.deletion.CASCADE, to='alumnos.ramo')),
            ],
        ),
    ]
