# Generated by Django 3.2.12 on 2024-05-31 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_auto_20240531_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnoseccion',
            name='id_alumno',
            field=models.ForeignKey(db_column='idRamo', on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno'),
        ),
    ]
